### ISSUE TITLE
ReqResp error message may be compressed

### ISSUE THREAD

**Issue by dapplion** [Consensys/teku#4463]
See https://github.com/ChainSafe/lodestar/issues/2622 the strange characters may be caused by snappy compression. The spec seems to indicate that the error message is a raw ByteList

**Comment by ajsutton** [comment]
hmm, my understanding was that all messages were snappy compressed - so the error message should be ssz encoded as `List[byte,256]` but then because this is ssz_snappy encoding strategy it would be passed through snappy frame based compression.  Certainly that would be preferable because otherwise you have to use ssz_snappy sometimes and just plain ssz encoding for error messages.

**Comment by ajsutton** [comment]
Going to close this one based on confirmation that Lighthouse is also expecting error responses to be snappy encoded. Give me a yell if I can help with anything though.

**Comment by dapplion** [comment]
Sound good, agree that the right implementation is to decode error messages based on the topic encoding :+1:
