### ISSUE TITLE
0 peers after unexpected reboot

### ISSUE THREAD

**Issue by alby6969** [Consensys/teku#4482]
### Description
Running Teku and Geth on my intel NUC i7 64G RAM 2TB NVME SSD - I do not know if there was a power outage or what, as my server is remote. The logs say there was a reboot at around Oct 13 19:34:03 . I got alerted to missed attestations when i woke up for maybe 1.5 hours. I logged in, updated Ubuntu with 5 updates and rebooted, and it picked up peers as normal again, this was at approx Oct 13 20:55

### Steps to Reproduce (Bug)
N/A - Has only happened once

**Expected behavior:** After unexpected reboot, expected Teku to automatically pick up peers, but stayed 0 until a manual reboot

**Actual behavior:** After unexpected reboot, Teku peers stayed 0

**Frequency:** Happened only once

### Versions (Add all that apply)
* Software version: 21.9.2
* Java version: "11.0.11" 2021-04-20
* OS Name & Version: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"

* Kernel Version: Linux eth 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* Virtual Machine software & version: N/A
* Docker Version: N/A
* Cloud VM, type, size: N/A

### Additional Information

I have attached the Geth and Teku logs, starting from right before the unexpected reboot at approx Oct 13 19:34:03 . 

The reboot at Oct 13 20:55 , was done by myself over ssh in order to pick up peers again
[tekulog.txt](https://github.com/ConsenSys/teku/files/7341973/tekulog.txt)
[gethlog.txt](https://github.com/ConsenSys/teku/files/7341974/gethlog.txt)

**Comment by ajsutton** [comment]
For the record, I think what's happening with your server is that the server and Teku start up before network connectivity is actually available.  That's quite unusual but certainly possible with some virtualisation and software defined network setups. It may also be that the external IP changes just after teku starts up which would have the same effect.  The attempt to do a discovery handshake with the bootnodes fails because the network isn't available initially and because that first failed handshake attempt didn't get cleaned up properly after failing future attempts to contact the bootnodes also failed so it was impossible to find peers even once the network came back up.

#4490 is a simple work around for this that was included in 21.10.0 release and #4497 fixes the actual underlying problem in the discovery library that will be included in the next release.
