### ISSUE TITLE
Continuous failure to produce attestations

### ISSUE THREAD

**Issue by paulmillr** [Consensys/teku#4516]
I'm testing teku behavior on prater testnet

### Steps to Reproduce (Bug)
1. Import 10 validators to teku. First 5 validators need to be already-validating. Import slashing protection from another client 
2. The other 5 validators need to be activating in some short time
3. Wait until activation.

**Expected behavior:** The new validators will produce attestations as expected

**Actual behavior:** all attestations will be missed. The attestations start missing 5 hours before the activation, even for existing validators

### Versions (Add all that apply)
* Software version: teku/v21.10.1/linux-x86_64/-debian-openjdk64bitservervm-java-17
* Java version: java 17
* OS Name & Version: debian 11
* Kernel Version: 5.10.0

### Additional Information

This seems like very bad bug, especially one week before altair launch. I have stopped testing this after 2+ hours, because nothing was produced. Switched to a different client, and all is fine.

The performance log is here: https://gist.github.com/paulmillr/da16133f9d010c866ddc1fd0fd4639ec

No errors, only lots of `SlashableConditionException` **after** attestations started dropping.

**Comment by ajsutton** [comment]
`SlashableConditionException` indicates that the node has refused to sign something because it would be potentially slash able. You definitely do NOT want teku to proceed to produce attestations in that case.

My guess is that the slashing protection file you imported includes attestations that are in the future.  Since Teku uses the minimal approach to slashing protection (which is much simpler, thus reliable and doesn't not consume an ever growing amount of disk space)  it will refuse to produce attestations until that future slot is passed.

It would be worth reviewing the attestations in the slashing protection file you imported to check if any are in the future - if so, teku is correctly preventing you from getting slashed.  You can also review the slashing protection records to see what Teku did import - they're simple YAML files under `<data-path>/validators/slashprotection/`.  Given this is the prater testnet if you're able to provide the slashing import file and resulting .yml files from that slashprotection directory we can review.

Also worth noting that Altair launched on the Prater testnet some time back.

**Comment by paulmillr** [comment]
> My guess is that the slashing protection file you imported includes attestations that are in the future. Since Teku uses the minimal approach to slashing protection (which is much simpler, thus reliable and doesn't not consume an ever growing amount of disk space) it will refuse to produce attestations until that future slot is passed.

I see stuff like that:

```
lastSignedBlockSlot: 1256396
lastSignedAttestationSourceEpoch: 47811
lastSignedAttestationTargetEpoch: 47812
---
lastSignedBlockSlot: 0
lastSignedAttestationSourceEpoch: 47811
lastSignedAttestationTargetEpoch: 47812
---
lastSignedBlockSlot: 1126761
lastSignedAttestationSourceEpoch: 47805
lastSignedAttestationTargetEpoch: 47810
---
lastSignedBlockSlot: 1201568
lastSignedAttestationSourceEpoch: 47811
lastSignedAttestationTargetEpoch: 47812
```

Seems fine. There are just 4 epochs there in sourceEpoch: 47805, 47807, 47810, 47811. After that i've switched to a different client.

> My guess is that the slashing protection file you imported includes attestations that are in the future

If it was, why did it validate fine for 5+ hours after import? It started missing attestations after that.

**Comment by ajsutton** [comment]
Ok, interesting. I think I'd need to see the full teku logs to dig in further.

**Comment by paulmillr** [comment]
No problem. How do I pass them to you?

**Comment by ajsutton** [comment]
You can email me at adrian.sutton@consensys.net is probably easiest.

**Comment by paulmillr** [comment]
Sent.

**Comment by ajsutton** [comment]
Ok, the log file shows that the node is failing to keep up with gossip:
```
2021-10-21 14:31:37.812+02:00 | beaconchain-async-13 | WARN  | Eth2TopicHandler | Encountered exception while processing message for topic /eth2/82f4a72b/beacon_attestation_16/ssz_snappy
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.util.concurrent.CompletionException: tech.pegasys.teku.service.serviceutils.ServiceCapacityExceededException: Failed to process signature, queue is full.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
```
and nearly every slot reports no block, I suspect because it's not getting them via gossip.  Eventually it falls far enough behind that the long sync kicks in and catches it back up to head, but in doing so the committee assignments change and often a validator is then assigned to attest at a different slot - that would be slash able so the slashing protection is correctly kicking in and stopping it.

We need to find out why its not able to keep up.

So a few questions:

1. What's the CPU and memory specs of the system it's running on?
2. Is there anything else running on that system? (Other beacon nodes, geth etc)
3. Have you set a -Xmx value at all for teku?

**Comment by paulmillr** [comment]
- Ryzen 7 1700X (8-core, 16-thread), 64GB RAM
- Geth is running (ate 1h of cpu time in 16h), other nodes are not. Prometheus is running, it ate just 2 mins of cpu time.
- The load was something like 5-5.5 with teku the last time i've checked

The teku is ran like this:

```
JAVA_OPTS=-Xmx2g
--rest-api-enabled=true --rest-api-docs-enabled=true --metrics-enabled --network=prater
```

**Comment by ajsutton** [comment]
Ah right, `-Xmx2g` will not be sufficient for a network the size of prater or mainnet.  Unfortunately a few guides have quite outdated values from when the networks were much smaller.

My suggestion would be to use:
```
Environment="JAVA_OPTS=-Xmx4g"
```

**Comment by paulmillr** [comment]
I can try it, but there were no memory errors. Why doesn't teku produce a mem error if something like this happens?

Can teku detect the total # of validators in the network and at least warn users accordingly?

**Comment by ajsutton** [comment]
> I can try it, but there were no memory errors. Why doesn't teku produce a mem error if something like this happens?
> 
> Can teku detect the total # of validators in the network and at least warn users accordingly?

There weren't any memory errors because teku didn't actually run out of memory - it just had to spend so much time doing garbage collection to survive it wasn't able to keep up. If that had been for a short period of time, that would be fine and it would have recovered, but the demand for memory just didn't subside.  If you think of it like when you've run more programs than can fit in system memory - you don't expect the system to fail, it starts using swap but that means everything gets slower.  That's essentially what teku is doing - it keeps dropping stuff out of memory to make room for stuff it needs now, but then has to reload those things from disk again when they're needed later, so it's effectively thrashing swap.

The logs are actually full of errors about the queue being full so it's immediately clear that it's not keeping up. That could be because of a lack of CPU or a lack of memory. The best way to monitor is via prometheus/grafana - our standard dashboard has a graph of time spent in GC which would very quickly show the problem.

**Comment by ajsutton** [comment]
I'm going to close this given that its clear the attestations weren't created because Teku didn't have sufficient resources to keep up with incoming gossip.  If you do increase the max heap and still have problems feel free to reopen.

**Comment by paulmillr** [comment]
Could teku emit any errors that would specifically mention that heap size should be increased ? Because gc time / size is not obvious

**Comment by ajsutton** [comment]
> Could teku emit any errors that would specifically mention that heap size should be increased ? Because gc time / size is not obvious

The problem with this is that the max heap size is a simple command line setting but the way it comes out inside the JVM varies depending on the JDK and which GC algorithm is in use (different GC algorithms take different approaches to memory management).  So this winds up being one of those things that's reasonably easy for a human to identify as a problem by looking at the standard dashboard we provide and seeing that CPU usage is very high and GC is is using nearly all of it, but much harder to identify programmatically from inside the JVM.

**Comment by paulmillr** [comment]
BTW, your dashboard inside of the repo is outdated. https://grafana.com/grafana/dashboards/13457 This one seems to be working
