### ISSUE TITLE
[MEV Boost\Builder] May be able to report the rewards we were paid from MEV at end of block duty

### ISSUE THREAD

**Issue by rolfyone** [Consensys/teku#5654]
from #5369

Reporting on duties has been aded to add EL gas used and block details, but the ticket also suggested having MEV rewards paid. That wasn't covered in the initial ticket, broken out here for tracking.

**Comment by StefanBratanov** [comment]
Since MEV Rewards are part of the `BuilderBid` which is not part of the `BeaconBlockBody` it is not straightforward to retrieve the builder bid for a particular block in the Validator Client. However as part of #5710 , we do log the `BuilderBid` details including the mev rewards. (that is in the Beacon Node)

**Comment by tbenr** [comment]
I think for the moment we can close this issue. The duties are on Validator client side but rewards are currently known only on Beacon Node. Moreover, as discussed widely on `block-construction` channel in Discord, logging the effective `feeRecipient` that has received the rewards is not something we can even try to do in  BN\VC.
